# Project: unitTest
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = build/main.o build/UnitTest.o build/FooTest.o build/BadmintonContainer.o build/BadmintonField.o build/BadmintonRun.o build/ConfigBadminton.o build/ConfigTool.o build/record.o build/TestConfigBadminton.o build/TestRecord.o build/TestBadmintonField.o build/TestBadmintonContainer.o
LINKOBJ  = build/main.o build/UnitTest.o build/FooTest.o build/BadmintonContainer.o build/BadmintonField.o build/BadmintonRun.o build/ConfigBadminton.o build/ConfigTool.o build/record.o build/TestConfigBadminton.o build/TestRecord.o build/TestBadmintonField.o build/TestBadmintonContainer.o
LIBS     = -L"d:/Program Files (x86)/Dev-Cpp/MinGW64/lib32" -L"d:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -m32 -g3
INCS     = -I"d:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"d:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"d:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/shuang/Desktop/GoodLuck/Coder/Cplus/Thoughtworks/badmintonManager/include" -I"C:/Users/shuang/Desktop/GoodLuck/Coder/Cplus/Thoughtworks/badmintonManager/src"
CXXINCS  = -I"d:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"d:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"d:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"d:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++" -I"C:/Users/shuang/Desktop/GoodLuck/Coder/Cplus/Thoughtworks/badmintonManager/include" -I"C:/Users/shuang/Desktop/GoodLuck/Coder/Cplus/Thoughtworks/badmintonManager/include" -I"C:/Users/shuang/Desktop/GoodLuck/Coder/Cplus/Thoughtworks/badmintonManager/src"
BIN      = unitTest.exe
CXXFLAGS = $(CXXINCS) -m32 -g3
CFLAGS   = $(INCS) -m32 -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

build/main.o: main.cpp
	$(CPP) -c main.cpp -o build/main.o $(CXXFLAGS)

build/UnitTest.o: UnitTest.cpp
	$(CPP) -c UnitTest.cpp -o build/UnitTest.o $(CXXFLAGS)

build/FooTest.o: FooTest.cpp
	$(CPP) -c FooTest.cpp -o build/FooTest.o $(CXXFLAGS)

build/BadmintonContainer.o: ../src/BadmintonContainer.cpp
	$(CPP) -c ../src/BadmintonContainer.cpp -o build/BadmintonContainer.o $(CXXFLAGS)

build/BadmintonField.o: ../src/BadmintonField.cpp
	$(CPP) -c ../src/BadmintonField.cpp -o build/BadmintonField.o $(CXXFLAGS)

build/BadmintonRun.o: ../src/BadmintonRun.cpp
	$(CPP) -c ../src/BadmintonRun.cpp -o build/BadmintonRun.o $(CXXFLAGS)

build/ConfigBadminton.o: ../src/ConfigBadminton.cpp
	$(CPP) -c ../src/ConfigBadminton.cpp -o build/ConfigBadminton.o $(CXXFLAGS)

build/ConfigTool.o: ../src/ConfigTool.cpp
	$(CPP) -c ../src/ConfigTool.cpp -o build/ConfigTool.o $(CXXFLAGS)

build/record.o: ../src/record.cpp
	$(CPP) -c ../src/record.cpp -o build/record.o $(CXXFLAGS)

build/TestConfigBadminton.o: TestConfigBadminton.cpp
	$(CPP) -c TestConfigBadminton.cpp -o build/TestConfigBadminton.o $(CXXFLAGS)

build/TestRecord.o: TestRecord.cpp
	$(CPP) -c TestRecord.cpp -o build/TestRecord.o $(CXXFLAGS)

build/TestBadmintonField.o: TestBadmintonField.cpp
	$(CPP) -c TestBadmintonField.cpp -o build/TestBadmintonField.o $(CXXFLAGS)

build/TestBadmintonContainer.o: TestBadmintonContainer.cpp
	$(CPP) -c TestBadmintonContainer.cpp -o build/TestBadmintonContainer.o $(CXXFLAGS)
